### ISSUE TITLE
Function for adding hosts/employees to Guest

### ISSUE THREAD

**Issue by carlosruiz2006** [bepsoccer/verkadaModule#160]
Could you please add a function for adding hosts/employees to Guest. This could open the gate for integration with HR management platforms like Kronos. Need an alternative to manual user creation, CSV upload or Azure AD SCIM snyc.

**Comment by carlosruiz2006** [comment]
Would you also be able to have a function that would get the list of hosts, and another to delete? that way one could potentially write a script that runs daily to sync the list with a 3rd party directory (different than Azure AD)

**Comment by bepsoccer** [comment]
[ ] Add-VerkadaWorkplaceEmployee
[ ] Get-VerkadaWorkplaceEmployee
[ ] Remove-VerkadaWorkplaceEmployee
[ ] Read-VerkadaWorkplaceEmployees

**Comment by bepsoccer** [comment]
specifying site by name should probably use the public API in the future, but for simplicity for now it will use the front end apis since the rest of these functions will be using the front end APIs.
